Repository ThingLog/ThingLog, pull requests merged in 2021-09, with the labels that each got.

#22 [#3] Core Data Modeling
  ThingLog.xcodeproj/project.pbxproj
  ThingLog.xcodeproj/xcshareddata/xcschemes/ThingLog.xcscheme
  ThingLog.xcodeproj/xcuserdata/jiwon.xcuserdatad/xcschemes/xcschememanagement.plist
  ThingLog/Model/CoreDataStack.swift
  ThingLog/SupportingFiles/AppDelegate.swift
  ThingLog/SupportingFiles/SceneDelegate.swift
  ThingLog/SupportingFiles/ThingLog.xcdatamodeld/.xccurrentversion
  ThingLog/SupportingFiles/ThingLog.xcdatamodeld/ThingLog.xcdatamodel/contents
  ThingLog/ThingLog.xcdatamodeld/ThingLog.xcdatamodel/contents
Labels: 🛠 feature

#10 [#4] TabBarController 구현 완료
  .gitignore
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/Assets.xcassets/categoryTab.imageset/Contents.json
  ThingLog/Assets.xcassets/categoryTab.imageset/categoryTab.png
  ThingLog/Assets.xcassets/categoryTab.imageset/categoryTab@2x.png
  ThingLog/Assets.xcassets/categoryTab.imageset/categoryTab@3x.png
  ThingLog/Assets.xcassets/homeTab.imageset/Contents.json
  ThingLog/Assets.xcassets/homeTab.imageset/homeTab.png
  ThingLog/Assets.xcassets/homeTab.imageset/homeTab@2x.png
  ThingLog/Assets.xcassets/homeTab.imageset/homeTab@3x.png
  ThingLog/Assets.xcassets/plusTab.imageset/Contents.json
  ThingLog/Assets.xcassets/plusTab.imageset/plusTab.png
  ThingLog/Assets.xcassets/plusTab.imageset/plusTab@2x.png
  ThingLog/Assets.xcassets/plusTab.imageset/plusTab@3x.png
  ThingLog/Coordinator/CategoryCoordinator.swift
  ThingLog/Coordinator/HomeCoordinator.swift
  ThingLog/SupportingFiles/SceneDelegate.swift
  ThingLog/View/ChoiceWritingView.swift
  ThingLog/ViewController/CategoryViewController.swift
  ThingLog/ViewController/HomeViewController.swift
  ThingLog/ViewController/TabBarController.swift
Labels: 🎨 view

#25 [#11] 홈화면 네비게이션바 및 프로파일 화면 구현 완료
  ThingLog.xcodeproj/project.pbxproj
  ThingLog.xcodeproj/xcshareddata/xcschemes/ThingLog 1.xcscheme
  ThingLog/View/ProfileView.swift
  ThingLog/ViewController/HomeViewController.swift
Labels: 🎨 view

#16 [#15] 홈화면 - 콘텐츠 화면 구현
  ThingLog.xcodeproj/project.pbxproj
  ThingLog.xcodeproj/xcshareddata/xcschemes/ThingLog.xcscheme
  ThingLog/Assets.xcassets/bought.imageset/Contents.json
  ThingLog/Assets.xcassets/bought.imageset/bought.png
  ThingLog/Assets.xcassets/bought.imageset/bought@2x.png
  ThingLog/Assets.xcassets/bought.imageset/bought@3x.png
  ThingLog/Assets.xcassets/gift.imageset/Contents.json
  ThingLog/Assets.xcassets/gift.imageset/gift.png
  ThingLog/Assets.xcassets/gift.imageset/gift@2x.png
  ThingLog/Assets.xcassets/gift.imageset/gift@3x.png
  ThingLog/Assets.xcassets/modifyText.imageset/Contents.json
  ThingLog/Assets.xcassets/modifyText.imageset/modifyText.png
  ThingLog/Assets.xcassets/modifyText.imageset/modifyText@2x.png
  ThingLog/Assets.xcassets/modifyText.imageset/modifyText@3x.png
  ThingLog/Assets.xcassets/setting.imageset/Contents.json
  ThingLog/Assets.xcassets/setting.imageset/setting.png
  ThingLog/Assets.xcassets/setting.imageset/setting@2x.png
  ThingLog/Assets.xcassets/setting.imageset/setting@3x.png
  ThingLog/Assets.xcassets/wish.imageset/Contents.json
  ThingLog/Assets.xcassets/wish.imageset/wish.png
  ThingLog/Assets.xcassets/wish.imageset/wish@2x.png
  ThingLog/Assets.xcassets/wish.imageset/wish@3x.png
  ThingLog/Extension/UIView+.swift
  ThingLog/View/ContentsTabView.swift
  ThingLog/View/ProfileView.swift
  ThingLog/View/TemplateImageButton.swift
  ThingLog/ViewController/ContentsCollection/BaseContentsCollectionViewController.swift
  ThingLog/ViewController/ContentsCollection/BoughtContentsCollectionViewController.swift
  ThingLog/ViewController/ContentsCollection/ContentsCollectionViewCell.swift
  ThingLog/ViewController/ContentsCollection/GiftContentsCollectionViewController.swift
  ThingLog/ViewController/ContentsCollection/WishContentsCollectionViewController.swift
  ThingLog/ViewController/ContentsPageViewController.swift
  ThingLog/ViewController/HomeViewController.swift
Labels: 🎨 view

#14 [#12] UserInformationViewModel 구현 완료
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/Extension/UserDefaults+.swift
  ThingLog/ViewModel/UserInformationViewModel.swift
Labels: 🛠 feature

#23 [#17 ,#18 ,#20 ,#21] fastlane 및 testflight 업로드 완료
  .gitignore
  Gemfile
  Gemfile.lock
  ThingLog.xcodeproj/project.pbxproj
  ThingLog.xcodeproj/xcshareddata/xcschemes/ThingLog-Debug.xcscheme
  ThingLog.xcodeproj/xcshareddata/xcschemes/ThingLog-Release.xcscheme
  ThingLog/Assets.xcassets/AppIcon.appiconset/100.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/1024.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/114.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/120.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/128.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/144.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/152.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/16.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/167.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/180.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/20.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/256.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/29.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/32.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/40.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/50.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/512.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/57.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/58.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/60.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/64.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/72.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/76.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/80.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/87.png
  ThingLog/Assets.xcassets/AppIcon.appiconset/Contents.json
  ThingLog/Info.plist
  ThingLog/SupportingFiles/en.lproj/InfoPlist.strings
  ThingLog/SupportingFiles/ko.lproj/InfoPlist.strings
  ThingLog/SupportingFiles/ko.lproj/LaunchScreen.strings
  ThingLogTests/Info.plist
  ThingLogUITests/Info.plist
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: 🖥 environment

#30 [#29] 기타: TextStyle 정의
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/Extension/UIFont+.swift
Labels: 🛠 feature
