Repository ThingLog/ThingLog, pull requests merged in 2021-10, with the labels that each got.

#57 홈: ChoiceWritingView에 들어가는 이미지 버튼 구현
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/Model/WriteType.swift
  ThingLog/View/ChoiceWritingView.swift
  ThingLog/View/WriteTypeButton.swift
Labels: 🎨 view

#58 [#56] feat: 홈 → 글쓰기 화면 이동
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/Coordinator/WriteCoordinator.swift
  ThingLog/View/ChoiceWritingView.swift
  ThingLog/ViewController/TabBarController.swift
  ThingLog/ViewController/WriteViewController+setup.swift
  ThingLog/ViewController/WriteViewController.swift
  ThingLog/ViewModel/WriteViewModel.swift
Labels: 🛠 feature

#67 [#66] ref: textfield 높이 조정
  ThingLog/View/SearchTextField.swift
Labels: ♻️ refactor

#72 [#71] 기타: CoreData 모델 선물 준 사람 항목 추가
  ThingLog/Entity/PostEntity+.swift
  ThingLog/Model/Post.swift
  ThingLog/SupportingFiles/ThingLog.xcdatamodeld/ThingLog.xcdatamodel/contents
Labels: 🛠 feature

#75 [#59, #60] 글쓰기: ThumbnailCell, CameraButtonCell 구현
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/Resource/Assets.xcassets/camera.imageset/Contents.json
  ThingLog/Resource/Assets.xcassets/camera.imageset/camera.png
  ThingLog/Resource/Assets.xcassets/camera.imageset/camera@2x.png
  ThingLog/Resource/Assets.xcassets/camera.imageset/camera@3x.png
  ThingLog/Resource/Assets.xcassets/closeBadge.imageset/Contents.json
  ThingLog/Resource/Assets.xcassets/closeBadge.imageset/closeBadge.png
  ThingLog/Resource/Assets.xcassets/closeBadge.imageset/closeBadge@2x.png
  ThingLog/Resource/Assets.xcassets/closeBadge.imageset/closeBadge@3x.png
  ThingLog/SwiftGen/ImageAssets.swift
  ThingLog/View/CollectionViewCell/CameraButtonCell.swift
  ThingLog/View/CollectionViewCell/ThumbnailCell.swift
Labels: 🎨 view

#80 [#79] 기타: CoreData Default Value 속성 수정
  ThingLog/Entity/PostEntity+.swift
  ThingLog/Model/Post.swift
  ThingLog/Model/PostType.swift
  ThingLog/SupportingFiles/ThingLog.xcdatamodeld/ThingLog.xcdatamodel/contents
  ThingLogTests/ThingLogPostRepositoryTests.swift
Labels: ♻️ refactor

#116 [#115] 카테고리: 카테고리 셀 구현
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/View/PaddingLabel.swift
  ThingLog/View/TableVeiwCell/CategoryCell.swift
Labels: 🎨 view

#112 [#107] 글쓰기: 카테고리 선택 셀
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/View/CollectionViewCell/SelectedCategoryCell.swift
  ThingLog/View/TableVeiwCell/WriteCategoryCell.swift
Labels: 🎨 view

#123 [#119] 기타: 카테고리 관련 파일 이름 변경
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/View/CollectionViewCell/LabelWithButtonRoundCollectionCell.swift
  ThingLog/View/TableVeiwCell/RoundLabelWithButtonTableCell.swift
  ThingLog/View/TableVeiwCell/WriteCategoryTableCell.swift
Labels: ♻️ refactor

#155 [#152] 카테고리: 카테고리 기능 구현
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/Extension/Notification.Name+.swift
  ThingLog/Model/Category.swift
  ThingLog/Repository/CategoryRepository.swift
  ThingLog/View/TableVeiwCell/WriteCategoryTableCell.swift
  ThingLog/ViewController/CategoryViewController.swift
  ThingLog/ViewModel/WriteViewModel.swift
Labels: 🛠 feature
