Repository ThingLog/ThingLog, pull requests merged in 2022-01, with the labels that each got.

#296 chore: add GoogleService-Info.plist
  GoogleService-Info.plist
Labels: 🖥 environment

#298 [#297] fastlane업데이트 및 gitignore 에 googleservice 추가
  .gitignore
  Gemfile.lock
  GoogleService-Info.plist
  ThingLog.xcodeproj/project.pbxproj
  ThingLog/SupportingFiles/Info.plist
  ThingLog/SwiftGen/ColorsAsset.swift
  ThingLog/SwiftGen/DrawersAssets.swift
  ThingLog/SwiftGen/Fonts.swift
  ThingLog/SwiftGen/FrameAssets.swift
  ThingLog/SwiftGen/IconsAssets.swift
  ThingLog/SwiftGen/ImageAssets.swift
  ThingLogTests/Info.plist
  ThingLogUITests/Info.plist
Labels: 🖥 environment

#300 [#299] env: firebase 라이센스 추가
  ThingLog/SupportingFiles/Settings.bundle/FirebaseLicense.plist
  ThingLog/SupportingFiles/Settings.bundle/LicenseList.plist
  ThingLog/SupportingFiles/Settings.bundle/en.lproj/Firebase.strings
Labels: 🖥 environment

#301 [#290] 기타: README 작성
  README.md
  image/1.png
  image/2.png
  image/3.png
  image/4.png
  image/5.png
  image/6.png
  image/Download_on_the_App_Store_Badge.svg
Labels: 📝 documentation

#315 [#302] 글쓰기: 물건 이름, 구매처 작성 필드에 붙여넣기, 잘라넣기 기능
  ThingLog/SwiftGen/ColorsAsset.swift
  ThingLog/SwiftGen/DrawersAssets.swift
  ThingLog/SwiftGen/Fonts.swift
  ThingLog/SwiftGen/FrameAssets.swift
  ThingLog/SwiftGen/IconsAssets.swift
  ThingLog/SwiftGen/ImageAssets.swift
  ThingLog/View/DisableSelectionTextField.swift
Labels: ♻️ refactor

#317 [#305] 글쓰기>사진: 사진이 여러 개 있을 때, 썸네일이 랜덤하게 노출되는 문제
  ThingLog/ViewController/ContentsCollection/BaseContentsCollectionViewController.swift
  ThingLog/ViewController/ContentsCollection/ContentsCollectionViewCell.swift
Labels: 🐛 bug, ♻️ refactor

#318 [#304] 포토카드: 여러 개의 사진이 있을 때 선택한 사진이 아니라 다른 사진이 표시되는 문제
  ThingLog/Entity/PostEntity+.swift
Labels: 🐛 bug

#319 [#288] 버그: 선택한 게시물로 제대로 이동하지 않는 문제
  ThingLog/ViewController/Post/PostViewController.swift
Labels: 🐛 bug

#320 [#309] 진열장: 블랙카드 획득 조건 = 기록의 합이 100만원 이상으로 변경
  ThingLog/Repository/DrawerCoreDataRepository.swift
  ThingLog/Repository/PostRepository.swift
Labels: 🐛 bug, 🛠 feature

#329 [#323] 설정: 다크모드 변경 시 모아보기 화면 업데이트
  ThingLog/ViewController/EasyLook/EasyLookViewController.swift
Labels: 🐛 bug

#330 [#324] 게시물 화면으로 이동할 때 첫번째 셀이 잔상으로 보이는 문제 해결
  ThingLog/ViewController/Post/PostViewController.swift
Labels: 🐛 bug

#331 [#311, #308] view: 뷰에 선 추가
  ThingLog/View/DropBoxView.swift
  ThingLog/View/DropDownView/DropDownView.swift
  ThingLog/ViewController/EasyLook/EasyLookViewController.swift
Labels: 🎨 view

#338 [#333] 포토카드: 로고 제거
  ThingLog/ViewController/PhotoCard/PhotoCardViewController+setup.swift
  ThingLog/ViewController/PhotoCard/PhotoCardViewController.swift
Labels: 🎨 view

#339 [#335] 알럿: 아니요/네 폰트타입 변경
  ThingLog/ViewController/AlertViewController.swift
Labels: 🎨 view

#341 [#307] 온보딩: 온보딩1 화면 수정
  ThingLog/Model/Constants.swift
  ThingLog/Resource/Icons.xcassets/ThingLog.imageset/ThingLog.png
  ThingLog/Resource/Icons.xcassets/ThingLog.imageset/ThingLog@2x.png
  ThingLog/Resource/Icons.xcassets/ThingLog.imageset/ThingLog@3x.png
  ThingLog/ViewController/Onboarding/OnboardingStartViewController.swift
Labels: 🎨 view

#342 [#294] 게시물: 게시물 이미지 카운트가 초기화 안되는 문제
  ThingLog/View/TableVeiwCell/PostTableCell/PostTableCell.swift
Labels: 🐛 bug
